config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "users#index"
resources :users, only: [:index, :create]
resources :players
resources :sessions, only: [:create]
get "log_out" => "sessions#destroy"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :player #queries which player the address belongs to.
  # This creates an instance mtd called 'player' that will be used for query
end

app/models/appearance.rb
class Appearance < ApplicationRecord
  # Holds the 'ids' of the 2 tables to be joined
  belongs_to :player
  belongs_to :game
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :appearances
   has_many :players, through: :appearances

end

app/models/player.rb
# The ORM(ActiveRec) maps the Player class to the players_table(migrations),
# and turns the fields to instances of this model
class Player < ApplicationRecord
    belongs_to :team
    has_one :address #This creates an instance mtd called 'address' that will be used for query
    # validations will run only on create and update,b4 saving to db
    has_many :appearances
    has_many :games, through: :appearances
    validates :first_name, :last_name, presence: true
    validates :age, presence: true, numericality:{greater_than: 0, less_than_or_equal_to: 100}
    
end
 

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :name, :email, presence: true
  validates :email, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }, length: {maximum: 50}
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        # find a user if a user is signed in
        User.find(session[:user_id]) if session[:user_id] 
        
    end
    def require_login
        # redirect to root page if session id is non existing
        unless session[:user_id]
            flash[:errors]=["You must login first"] 
        redirect_to root_path 
        end
    end
    
    
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :require_login
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.fetch(:player, {})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        # find who a particular user is thru email column
        @user = User.find_by(email: params[:email])
        # if user found
        if @user and @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to players_path
        else
            flash[:errors]=["Invalid combination"] 
            redirect_back(fallback_location: root_path)  
            
        end
        
        
    end
    def destroy
        reset_session
        redirect_to :root
        
    end
    
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @user = User.new
        
    end
    def create
        @user = User.new(user_params)
        
        if @user.save
            # Save the user created to session for something later
            # We call the key 'user_id' stored in the session hash
            session[:user_id] = @user.id
            redirect_to players_path
            
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to action: :index
            
        end
        
        
    end
    
    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
        
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>league</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Players</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Player', new_player_path %>
<%= link_to 'Log Out', "/log_out" %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/users/index.html.erb
<h1 class="text-center">Login and Redg</h1>
<div class="container">
  <% if flash[:errors] %>
    <div class="row">
      <% flash[:errors].each do |error| %>
        <p class="text-danger"><%= error %></p>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <p class="lead text-muted">Registration</p>
      <%= form_for @user do |f| %>
        <%# <%= render 'layouts/error_messages', f: f.object %>
        <div class="form-group">
          <%=  f.label :name %>
          <%=  f.text_field :name %>
        </div>
        <div class="form-group">
          <%=  f.label :email %>
          <%=  f.email_field :email %>
        </div>
        <div class="form-group">
          <%=  f.label :password %>
          <%=  f.password_field :password %>
        </div>
        <div class="form-group">
          <%=  f.label :password_confirmation %>
          <%=  f.password_field :password_confirmation %>
        </div>
        <%=  f.submit "Create User"  %>
      <% end %>
    </div>
    <div class="col-md-6">
      <p class="lead text-muted">Login</p>
      <%= form_tag sessions_path do %>
        <div class="form-group">
          <%=  label_tag :email %>
          <%=  email_field_tag :email %>
        </div>
        <div class="form-group">
          <%=  label_tag :password %>
          <%=  password_field_tag :password %>
        </div>
        <%=  submit_tag "Sign In"  %>
      <% end %>
    </div>
  </div>
</div>